name: Release Bot

on:
  push:
    branches:
      - master

jobs:
  Windows-x64:
    runs-on: windows-latest

    steps:
      - name: Checkout Era.js
        uses: actions/checkout@v2
        with:
          repository: miswanting/Era.js
          path: Era.js

      - name: Checkout Era.js-SDK
        uses: actions/checkout@v2
        with:
          path: Era.js-SDK

      - name: Setup Node.js Enviroment
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - name: Setup Python 3 Enviroment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Prebuild Front-End
        run: |
          cd Era.js\Next\FrontEnd
          npm run setup
          npx electron-builder --dir

      - name: Assemble SDK
        run: |
          $date = Get-Date -Format "yyMMdd"
          echo "::set-env name=RELEASE_DATE::$date"
          echo "::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}"
          mkdir Era.js-SDK\erajs
          xcopy Era.js\Next\BackEnd\erajs Era.js-SDK\erajs\ /E
          Remove-Item Era.js-SDK\prebuilt\*.* -Recurse
          xcopy Era.js\Next\FrontEnd\dist\win-unpacked Era.js-SDK\prebuilt\ /E
          Compress-Archive -Path Era.js-SDK\* -DestinationPath "Era.js-SDK-v$date.x64.zip" -CompressionLevel Optimal

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.RELEASE_DATE }}
          release_name: Era.js-SDK v${{ env.RELEASE_DATE }}
          body_path: Era.js-SDK\CHANGELOG.md
          draft: true
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "Era.js-SDK-v${{ env.RELEASE_DATE }}.x64.zip"
          asset_name: "Era.js-SDK-v${{ env.RELEASE_DATE }}.x64.zip"
          asset_content_type: application/zip

  Windows-x86:
    runs-on: windows-latest

    steps:
      - name: Checkout Era.js
        uses: actions/checkout@v2
        with:
          repository: miswanting/Era.js
          path: Era.js

      - name: Checkout Era.js-SDK
        uses: actions/checkout@v2
        with:
          path: Era.js-SDK

      - name: Setup Node.js Enviroment
        run: dir

      - name: Setup Python 3 Enviroment
        run: dir
  # Release Linux x64:
  # Release Linux x32:
